import type { Metadata } from "next";
import Inter from "next/font/local";
import "./globals.css";

const inter = Inter({
  display: "swap",
  src: "./fonts/Inter.ttf",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.className}`}>{children}</body>
    </html>
  );
}
